[tool.poetry]
name = "textual_budget"
version = "0.1.0"
description = ""
authors = ["Adam K. <arkelly2@medicine.wisc.edu>"]
readme = "README.md"
packages = [{include = "textual_budget"}]

[tool.poetry.dependencies]
python = "^3.11"
textual-dev = "^1.2.1"
textual = "^0.38.1"




[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
