SELECT_OPTIONS: list[tuple[str, str]] = [
    ("Discover Card", "Discover Card"),
    ("JPMorgan Chase - Mortgage", "JPMorgan Chase - Mortgage"),
    ("N. Student Loan Bill", "N. Student Loan Bill"),
    ("Netflix", "Netflix"),
    ("T-Mobile Internet", "T-Mobile Internet"),
    ("A. Federal Student Loan", "A. Federal Student Loan"),
    ("Linchpin", "Linchpin"),
    ("Adam Paycheck", "Adam Paycheck"),
    ("Nicole Paycheck", "Nicole Paycheck"),
    ("Alliant Energy", "Alliant Energy"),
    ("Private Adam Student Loan", "Private Adam Student Loan"),
    ("Project Fi", "Project Fi"),
    ("Progressive Insurance", "Progressive Insurance"),
    (
        "City of Janesville (water/sewer/garbage)",
        "City of Janesville (water/sewer/garbage)",
    ),
    ("Google Storage", "Google Storage"),
    ("Spotify", "Spotify"),
    ("Groceries/House Supplies", "Groceries/House Supplies"),
    ("Dog Food", "Dog Food"),
    ("Gas", "Gas"),
    ("Eating Out", "Eating Out"),
    ("Dog", "Dog"),
    ("Money towards savings", "Money towards savings"),
    ("Daycare expenses", "Daycare expenses"),
    ("Miscellaneous", "Miscellaneous"),
    ("Car Expenses", "Car Expenses"),
    ("House Reno", "House Reno"),
    ("Medical", "Medical"),
]

